server:
  port: 8080

spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进Eurekaserver默认为true。
    fetch-registry: true  #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002.com:7002/eureka