server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向服务注册中心注册自己
    register-with-eureka: false
      #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false #要不要去注册中心获取其他服务的地址
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。
      #集群指向其它eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/
  #server:
    #关闭自我保护模式
    #enable-self-preservation: false
    #表示 Eureka Server 清理无效节点的频率
    #eviction-interval-timer-in-ms: 2000
